#  items.http
### create
POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Mouse",
    "amount": 10,
    "quantity" : 10
}
### find all
GET http://localhost:3000/items

### find one
GET http://localhost:3000/items/2
### update
PATCH http://localhost:3000/items/2
Content-Type: application/json

{
    "title": "Mouse wireless"
   
}
### delete
DELETE http://localhost:3000/items/2
### validation

### find one by string
GET http://localhost:3000/items/A

### create with wrong amount number type
POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Printer",
    "amount": "SHOUD_BE_NUM",
    "price": 5000    
}
