# users.http
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "A5",
    "password": "1234",
    "role": "USER"
}
###
### Admin Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Admin01",
    "password": "1234",
    "role": "ADMIN"
}
###
### Manager Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "m1001",
    "password": "changeit",
    "role": "MANAGER"
}