# users.http
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "user01",
    "password": "1234",
    "role": "USER"
}
###
### Admin Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "admin01",
    "password": "1234",
    "role": "ADMIN"
}
###
### Manager Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "manager01",
    "password": "changeit",
    "role": "MANAGER"
}
### find all
GET http://localhost:3000/users

### find one
GET http://localhost:3000/users/10
### update
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
    "title": "Mouse wireless"
   
}
### delete
DELETE http://localhost:3000/users/2